name: podpeace
options:
  bundleIdPrefix: com.personal
  deploymentTarget:
    iOS: "18.0"
  generateEmptyDirectories: true

packages:
  FeedKit:
    url: https://github.com/nmdias/FeedKit
    from: "9.1.2"

settings:
  base:
    SWIFT_VERSION: "6.2"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: SHQSDJG35Q

targets:
  PodPeace:
    type: application
    platform: iOS
    sources:
      - PodPeace
    dependencies:
      - package: FeedKit
    settings:
      base:
        INFOPLIST_FILE: PodPeace/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.personal.podpeace
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        MARKETING_VERSION: "0.5"
        CURRENT_PROJECT_VERSION: "1"
    info:
      path: PodPeace/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen:
          UIColorName: ""
        UIBackgroundModes:
          - audio
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleDisplayName: Pod Peace

schemes:
  PodPeace:
    build:
      targets:
        PodPeace: all
    run:
      config: Debug
